### ISSUE TITLE
OSI七层模型的图片加载不完整

### ISSUE THREAD

**Issue by MrTreasure** [laoqiren/web-performance#4]
在[带宽与延迟](https://github.com/laoqiren/web-performance/blob/master/%E5%B8%A6%E5%AE%BD%E4%B8%8E%E5%BB%B6%E8%BF%9F/README.md)中的图片因为是gif格式，我打开发现没有加载完，建议换成github的链接

**Comment by laoqiren** [comment]
部分文章中图片确实存在问题，后续会完善，谢谢指出
