### ISSUE TITLE
img from alinode site failed to load 

### ISSUE THREAD

**Issue by C-ra-ZY** [laoqiren/web-performance#5]
https://github.com/laoqiren/web-performance/blob/master/%E9%AB%98%E6%80%A7%E8%83%BDJavaScript/GC%E6%9C%BA%E5%88%B6.md

**Comment by laoqiren** [comment]
Thanks for your issue, I'll fix it.

**Comment by laoqiren** [comment]
@C-ra-ZY Hi, the issue has been fixed, thanks again.

**Comment by C-ra-ZY** [comment]
thank you for such a quick response. and i think you can close this issue.

**Comment by laoqiren** [comment]
@C-ra-ZY Yeah.
